script(main)
{
  local
  {
  };
  onmessage("start")
  {
    bindui(@window){
      onevent("button","cont","Button");
    };
    @window.SetActive(changetype(0,"bool"));
  };
  onmessage("show_failed")
  {
    @window.SetActive(changetype(1,"bool"));
  };
  onnamespacedmessage("on_click")args($tag,$inputs,$toggles,$sliders,$dropdowns)
  {
    @window.SetActive(changetype(0,"bool"));
    if($tag=="cont"){
      firemessage("on_failed_button_click");
    };
  };
};